const express = require('express'); const http = require('http'); const { Server } = require('socket.io'); const path = require('path');
const { createRoom, joinRoom, updateSettings, startGame, gameAction, resetRoom, removePlayer, publicRoom } = require('./rooms'); const { getMode } = require('./modes');
const app = express(); const server = http.createServer(app); const io = new Server(server); app.use(express.static(path.join(__dirname, 'public')));
function emitState(room, state) { io.to(room.code).emit('game-state', state || getMode(room.modeId).engine.getPublicState(room)); }
io.on('connection', socket => {
 socket.on('create-room', ({ name, modeId }) => { const r = createRoom(socket.id, String(name || '').trim(), modeId); if (r.error) return socket.emit('join-error', { message: r.error }); socket.join(r.room.code); socket.emit('room-joined', publicRoom(r.room)); });
 socket.on('join-room', ({ code, name }) => { const r = joinRoom(String(code || '').toUpperCase(), socket.id, String(name || '').trim()); if (r.error) return socket.emit('join-error', { message: r.error }); socket.join(r.room.code); socket.emit('room-joined', publicRoom(r.room)); socket.to(r.room.code).emit('room-updated', publicRoom(r.room)); });
 socket.on('update-settings', ({ code, settings }) => { const r = updateSettings(code, socket.id, settings); if (r.error) return socket.emit('start-error', { message: r.error }); io.to(r.room.code).emit('room-updated', publicRoom(r.room)); });
 socket.on('start-game', ({ code }) => { const r = startGame(code, socket.id); if (r.error) return socket.emit('start-error', { message: r.error }); (r.privateAssignments || []).forEach(a => io.to(a.playerId).emit('game-private', a)); emitState(r.room, r.publicState); });
 socket.on('game-action', ({ code, action, payload }) => { const r = gameAction(code, socket.id, action, payload); if (r.error) return socket.emit('game-error', { message: r.error }); emitState(r.room, r.publicState); if (r.results) io.to(r.room.code).emit('game-results', r.results); if (r.sessionComplete) io.to(r.room.code).emit('session-complete'); });
 socket.on('play-again', ({ code }) => { const r = resetRoom(code, socket.id); if (r.error) return socket.emit('start-error', { message: r.error }); io.to(r.room.code).emit('room-reset', publicRoom(r.room)); });
 socket.on('disconnect', () => { const r = removePlayer(socket.id); if (!r || r.roomDeleted) return; io.to(r.room.code).emit('room-updated', publicRoom(r.room)); if (r.aborted) return io.to(r.room.code).emit('game-aborted', { room: publicRoom(r.room), message: 'Not enough players to continue. Back to the lobby.' }); emitState(r.room, r.publicState); if (r.results) io.to(r.room.code).emit('game-results', r.results); });
});
server.listen(process.env.PORT || 3000, () => console.log('Server running at http://localhost:3000'));
